version: "3.8"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pepper
      - POSTGRES_USER=pepper
      - POSTGRES_PASSWORD=pepper

  redis:
    image: redis
    ports:
      - "6379:6379"

  django:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
